<div class="row">
    <div class="col-12 py-5 text-center">
        <h1><?php echo $lang['page-not-found']; ?></h1>
    </div>
    <div class="col-12 text-center">
        <a href="<?php $gs->getPathFor('index'); ?>" class="btn btn-primary btn-lg" role="button" aria-pressed="true"><i class="fas fa-inverse fa-home" aria-hidden="true"></i> <?php echo $lang['back-to-hp']; ?></a>
    </div>
</div>
