<div class="row justify-content-center">
    <div class="col-12 col-md-8 col-xl-6 pb-5">
        <h1 class="text-center"><?= $lang['link-about']; ?></h1>
        <p>
            Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt 
            ut labore et dolore magna aliquyam erat, sed diam voluptua.
        </p>
        <p>
            Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt 
            ut labore et dolore magna aliquyam erat, sed diam voluptua.
        </p>
    </div>
</div>