<div class="row">
    <div class="col-12 pb-5 text-center">
        <h1>
            <?= $lang['meta-title']; ?>&nbsp;&nbsp;
            <a href="https://github.com/CodelineRed/gulp-skeleton" target="_blank"><span data-bs-toggle="tooltip" data-bs-placement="bottom" title="GitHub"><i class="fab fa-inverse fa-github" aria-hidden="true"></i></span></a>
        </h1>
    </div>
</div>
<div class="row text-center justify-content-center">
    <div class="col-12">
        <span style="font-size: 1.75rem;"><?= $lang['included']; ?></span>
    </div>
    <div class="col-12 col-md-8 pb-5">
        <div class="slider slider-brands" data-slick='{"responsive": [{"breakpoint": 575,"settings": {"slidesToShow": 2, "slidesToScroll": 1}},{"breakpoint": 991, "settings": {"slidesToShow": 3, "slidesToScroll": 1}}]}'>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-bold"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="far fa-square"></i>
                    <i class="fas fa-bold fa-inverse" data-fa-transform="shrink-6"></i>
                </div>
                <a href="https://getbootstrap.com/" target="_blank" class="d-block label"><?= $lang['bootstrap']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-font-awesome-flag"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="far fa-square"></i>
                    <i class="fab fa-font-awesome-flag fa-inverse" data-fa-transform="shrink-6"></i>
                </div>
                <a href="https://fontawesome.com/" target="_blank" class="d-block label"><?= $lang['fontawesome']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-images"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="fas fa-square"></i>
                    <i class="fas fa-image fa-inverse" data-fa-transform="shrink-7"></i>
                    <i class="fas fa-chevron-left fa-inverse" data-fa-transform="shrink-13 left-6"></i>
                    <i class="fas fa-chevron-right fa-inverse" data-fa-transform="shrink-13 right-6"></i>
                </div>
                <a href="http://kenwheeler.github.io/slick/" target="_blank" class="d-block label"><?= $lang['slick']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-image"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="fas fa-square"></i>
                    <i class="fas fa-image fa-inverse" data-fa-transform="shrink-4"></i>
                    <i class="fas fa-sync" data-fa-transform="shrink-12 up-2.75 right-3.8"></i>
                </div>
                <a href="https://www.andreaverlicchi.eu/lazyload/" target="_blank" class="d-block label"><?= $lang['lazyload']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-css3"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="fas fa-square"></i>
                    <i class="fas fa-user-secret fa-inverse" data-fa-transform="shrink-4"></i>
                    <i class="fab fa-css3" data-fa-transform="shrink-14 down-4 right-3.5"></i>
                    <i class="fab fa-html5" data-fa-transform="shrink-14 down-4 left-3.5"></i>
                </div>
                <a href="https://www.npmjs.com/package/cssuseragent" target="_blank" class="d-block label"><?= $lang['cssua']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-cookie"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="fas fa-circle"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 up-4 left-4"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 down-0 left-5.5"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 down-4.2 right-4"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-13 down-4 left-2"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-13"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-14 right-5"></i>
                    <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-14 up-5"></i>
                </div>
                <a href="https://github.com/insites/cookieconsent" target="_blank" class="d-block label"><?= $lang['cookieconsent']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-5x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-black-tie"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-layers fa-10x">
                    <i class="far fa-square"></i>
                    <i class="fab fa-black-tie fa-inverse" data-fa-transform="shrink-6"></i>
                </div>
                <a href="https://fancyapps.com/" target="_blank" class="d-block label"><?= $lang['fancyapps']; ?></a>
            </div>
        </div>
    </div>
    <div class="col-12 pb-5">
        <div class="row">
            <div class="col-12 col-md-6 pb-5 pb-md-0">
                <!-- Ultimate Question of Life, the Universe, and Everything -->
                <h3 class="pb-2"><?= $lang['lazyload-example']; ?></h3>
                <a href="https://picsum.photos/id/82/1920/1080" data-fancybox="demo" data-caption="<?= $lang['gallery-caption-1']; ?>">
                    <img src="<?= str_replace(['%w', '%h'], [798, 420], $imagePlaceholder); ?>" data-src="https://via.placeholder.com/266x140/2e2e2e/fff?text=<?= $lang['open-gallery']; ?>" alt="image" class="img-fluid lazy"/>
                </a>
                <div class="d-none">
                    <a href="https://picsum.photos/id/64/1920/1080" data-fancybox="demo" data-caption="<?= $lang['gallery-caption-2']; ?>">
                        <img src="https://via.placeholder.com/266x140/1a0e0e/fff?text=Image%202" alt="image"/>
                    </a>
                    <a href="https://picsum.photos/id/120/1920/1080" data-fancybox="demo" data-caption="<?= $lang['gallery-caption-3']; ?>">
                        <img src="https://via.placeholder.com/266x140/0e1a12/fff?text=Image%203" alt="image"/>
                    </a>
                    <a href="https://picsum.photos/id/147/1920/1080" data-fancybox="demo" data-caption="<?= $lang['gallery-caption-4']; ?>">
                        <img src="https://via.placeholder.com/266x140/0e0e1a/fff?text=Image%204" alt="image"/>
                    </a>
                    <a href="https://picsum.photos/id/190/1920/1080" data-fancybox="demo" data-caption="<?= $lang['gallery-caption-5']; ?>">
                        <img src="https://via.placeholder.com/266x140/2a1b2f/fff?text=Image%205" alt="image"/>
                    </a>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <h3 class="pb-2"><?= $lang['cssua-monitor']; ?></h3>
                <div class="cssua-monitor"></div>
            </div>
        </div>
    </div>
</div>
