# ---- Unix ----
# systemctl docker start
# docker run --rm --interactive --tty --volume #PWD:/app composer create-project --ignore-platform-reqs --no-dev codelinered/gulp-skeleton gulp-skeleton "dev-production"
# ---- Windows CMD ----
# "c:\path\to\Docker Desktop.exe"
# docker run --rm --interactive --tty --volume %cd%:/app composer create-project --ignore-platform-reqs --no-dev codelinered/gulp-skeleton gulp-skeleton "dev-production"
# --- All OS ----
# cd gulp-skeleton
# docker-compose up -d

version: '3'

volumes:
    logs:
        driver: local

# docker-compose up -d
services:
    # http://localhost:7701
    # docker exec -ti gulp-skeleton php --version
    webserver:
        image: php:8-alpine
        container_name: gulp-skeleton
        working_dir: /var/www
        command: php -S 0.0.0.0:80 -t public
        environment:
            docker: "true"
        ports:
            - 7701:80
        volumes:
            - .:/var/www
            - logs:/var/www/logs
