<!DOCTYPE html>
<html class="no-js">
    <head>
        <script>
            function setCookie(e,t,n){var o=new Date;o.setTime(o.getTime()+24*n*60*60*1e3);var i="expires="+o.toUTCString();document.cookie=e+"="+t+";"+i+";path=/"}function getCookie(e){for(var t=e+"=",n=decodeURIComponent(document.cookie).split(";"),o=0;o<n.length;o++){for(var i=n[o];" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(t))return i.substring(t.length,i.length)}return""}
            var cookiesAllowed = getCookie('cookieconsent_status') !== 'deny';
        </script>
        <?php
        // if user clicked not deny
        $cookiesAllowed = isset($_COOKIE['cookieconsent_status']) && in_array($_COOKIE['cookieconsent_status'], array('allow', 'dismiss')) ? TRUE : FALSE;
        
        // default setting (home page)        
        $meta = array(
            'title' => 'Gulp Templating - InsanityMeetsHH',
            'baseUrl' => 'https://gulp.insanitymeetshh.net/',
            'currentUrl' => ($_SERVER['SERVER_PORT'] == '80' ? 'http' : 'https') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'],
            'keywords' => '',
            'description' => '',
            'robots' => 'index,follow',
            'author' => 'InsanityMeetsHH',
            'fbAppId' => '',
            'fbAdmins' => '',
            'publisher' => '',
            'type' => 'website',
            'socialMediaImage' => '',
            'siteName' => 'Gulp Templating',
            'twitterSite' => 'InsanityMeetsHH',
            'twitterUrl' => 'https://twitter.com/InsanityMeetsHH',
            'rssUrl' => '',
            'locale' => 'de_DE',
            'themeColor' => '#212121',
        );
        ?>
        
        <title><?php echo $meta['title']; ?></title>
        <base href="<?php echo $meta['baseUrl']; ?>">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="keywords" content="<?php echo $meta['keywords']; ?>"/>
        <meta name="description" content="<?php echo $meta['description']; ?>">
        <meta name='robots' content="<?php echo $meta['robots']; ?>">
        <meta name="author" content="<?php echo $meta['author']; ?>">
        <meta property="fb:admins" content="<?php echo $meta['fbAdmins']; ?>"/>
        <meta property="fb:app_id" content="<?php echo $meta['fbAppId']; ?>"/>
        <meta property="og:type" content="<?php echo $meta['type']; ?>"/>
        <meta property="og:title" content="<?php echo $meta['title']; ?>"/>
        <meta property="og:description" content="<?php echo $meta['description']; ?>"/>
        <meta property="og:image" content="<?php echo $meta['socialMediaImage']; ?>"/>
        <meta property="og:site_name" content="<?php echo $meta['siteName']; ?>"/>
        <meta property="og:url" content="<?php echo $meta['currentUrl']; ?>"/>
        <meta property="og:locale" content="<?php echo $meta['locale']; ?>"/>
        <meta property="article:publisher" content="<?php echo $meta['publisher']; ?>"/>
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="<?php echo $meta['twitterSite']; ?>">
        <meta name="twitter:title" content="<?php echo $meta['title']; ?>">
        <meta name="twitter:description" content="<?php echo $meta['description']; ?>">
        <meta name="twitter:image" content="<?php echo $meta['socialMediaImage']; ?>">
        <link rel="me" href="<?php echo $meta['twitterUrl']; ?>">
        <link rel="canonical" href="<?php echo $meta['currentUrl']; ?>"/>
        <link rel="alternate" hreflang="x-default" href="<?php echo $meta['currentUrl']; ?>"/>
        <link rel="alternate" type="application/rss+xml" title="" href="<?php echo $meta['rssUrl']; ?>"/>
        <?php /** Favicon sizes 16, 32, 36, 48, 70, 72, 96, 144, 150, 180, 192, 256, 310, 310x150, 384, 512, SVG, ICO */ ?>
        <link rel="apple-touch-icon" href="img/favicons/favicon-180x180.png" sizes="180x180">
        <link rel="icon" type="image/png" href="img/favicons/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="img/favicons/favicon-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="img/favicons/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="img/favicons/manifest.json">
        <link rel="mask-icon" href="img/favicons/favicon.svg" color="<?php echo $meta['themeColor']; ?>">
        <meta name="msapplication-TileColor" content="<?php echo $meta['themeColor']; ?>">
        <meta name="msapplication-TileImage" content="img/favicons/favicon-144x144.png">
        <meta name="msapplication-config" content="img/favicons/browserconfig.xml">
        <meta name="theme-color" content="<?php echo $meta['themeColor']; ?>">
        <link rel="shortcut icon" href="img/favicons/favicon.ico">
        
        <link rel="stylesheet" href="css/styles.css?v=3.0.4">
        <script>
            // if cookies allowed - load tracking code
            if (cookiesAllowed) {
                // Google Analaytics, Google Tag Manager, ...
//                var s = document.createElement('script');
//                s.type = 'text/javascript';
//                s.async = true;
//                s.src = 'https://www.googletagmanager.com/gtag/js?id=UA-NUMBER-X';
//                var h = document.getElementsByTagName('head')[0];
//                h.appendChild(s, h);
//            
//                window.dataLayer = window.dataLayer || [];
//                function gtag(){dataLayer.push(arguments);}
//                gtag('js', new Date());
//                gtag('config', 'UA-NUMBER-X', {'anonymize_ip': true});
            }
        </script>
    </head>
    <body>
        <div class="container">
            <?php include __DIR__ . '/../' . $template . '.phtml'; ?>
        </div>
        <script type="text/javascript" src="js/scripts.js?v=3.0.4"></script>
    </body>
</html>