<!DOCTYPE html>
<html class="no-js">
    <head>
        <title>Gulp Templating - InsanityMeetsHH</title>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <?php include __DIR__ . '/../' . $template . '.phtml'; ?>
        <script type="text/javascript" src="js/scripts.js"></script>
    </body>
</html>