<div class="container">
    <div class="row">
        <div class="col-12 py-5 text-center"><h1>
                Gulp Templating - InsanityMeetsHH
                <a href="https://github.com/InsanityMeetsHH/gulp-templating" target="_blank"><i class="fab fa-inverse fa-github" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="GitHub"></i></a>
            </h1></div>
    </div>
    <div class="row text-center align-items-center justify-content-center">
        <div class="col-12">
            <span style="font-size: 1.75rem;">included</span>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="slider-brands">
                <div class="slider-item">
                    <!-- Fonts with CSS Example (use only without node_modules/@fortawesome/fontawesome-free/js/all.js) -->
                    <!--<span class="fa-stack fa-3x">
                        <i class="far fa-stack-2x fa-square"></i>
                        <i class="fas fa-stack-1x fa-inverse fa-bold"></i>
                    </span><br/>-->

                    <!-- SVG with JavaScript Example (use only with node_modules/@fortawesome/fontawesome-free/js/all.js) -->
                    <div class="fa-10x">
                        <span class="fa-layers">
                            <i class="far fa-square"></i>
                            <i class="fas fa-bold fa-inverse" data-fa-transform="shrink-6"></i>
                        </span>
                    </div>
                    <a href="https://getbootstrap.com/" target="_blank" class="d-block label">Bootstrap 4</a>
                </div>
                <div class="slider-item">
                    <!-- Fonts with CSS Example (use only without node_modules/@fortawesome/fontawesome-free/js/all.js) -->
                    <!--<span class="fa-stack fa-3x">
                        <i class="far fa-stack-2x fa-square"></i>
                        <i class="fab fa-stack-1x fa-inverse fa-font-awesome-flag"></i>
                    </span><br/>-->

                    <!-- SVG with JavaScript Example (use only with node_modules/@fortawesome/fontawesome-free/js/all.js) -->
                    <div class="fa-10x">
                        <span class="fa-layers">
                            <i class="far fa-square"></i>
                            <i class="fab fa-font-awesome-flag fa-inverse" data-fa-transform="shrink-6"></i>
                        </span>
                    </div>
                    <a href="https://fontawesome.com/" target="_blank" class="d-block label">Fontawesome 5</a>
                </div>
                <div class="slider-item">
                    <!-- Fonts with CSS Example (use only without node_modules/@fortawesome/fontawesome-free/js/all.js) -->
                    <!--<span class="fa-stack fa-3x">
                        <i class="far fa-stack-2x fa-square"></i>
                        <i class="fas fa-stack-1x fa-inverse fa-images"></i>
                    </span><br/>-->

                    <!-- SVG with JavaScript Example (use only with node_modules/@fortawesome/fontawesome-free/js/all.js) -->
                    <div class="fa-10x">
                        <span class="fa-layers">
                            <i class="far fa-square"></i>
                            <i class="fas fa-images fa-inverse" data-fa-transform="shrink-7 left-1"></i>
                        </span>
                    </div>
                    <a href="http://kenwheeler.github.io/slick/" target="_blank" class="d-block label">Slick Carousel</a>
                </div>
            </div>
        </div>
    </div>
</div>
