<div class="container">
    <div class="row">
        <div class="col-12 py-5 text-center"><h1>
                Gulp Templating - InsanityMeetsHH
                <a href="https://github.com/InsanityMeetsHH/gulp-templating" target="_blank"><i class="fab fa-inverse fa-github" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="GitHub"></i></a>
            </h1></div>
    </div>
    <div class="row text-center align-items-center">
        <div class="col-12 col-md-2 pb-5 order-1 order-md-2"><span style="font-size: 1.75rem;">included</span></div>
        <div class="col-6 col-md-3 offset-md-2 order-1 order-md-1">
            <span class="fa-stack fa-3x">
                <i class="far fa-stack-2x fa-square"></i>
                <i class="fas fa-stack-1x fa-inverse fa-bold"></i>
            </span><br/>
            <a href="https://getbootstrap.com/" target="_blank" class="d-inline-block p-3">Bootstrap 4</a>
        </div>
        <div class="col-6 col-md-3 order-3 order-md-3">
            <span class="fa-stack fa-3x">
                <i class="far fa-stack-2x fa-square"></i>
                <i class="fab fa-stack-1x fa-inverse fa-font-awesome-flag"></i>
            </span><br/>
            <a href="https://fontawesome.com/" target="_blank" class="d-inline-block p-3">Fontawesome 5</a>
        </div>
    </div>
</div>