<div class="row">
    <div class="col-12 py-5 text-center"><h1>
            Gulp Templating - InsanityMeetsHH
            <a href="https://github.com/InsanityMeetsHH/gulp-templating" target="_blank"><i class="fab fa-inverse fa-github" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="GitHub"></i></a>
        </h1></div>
</div>
<div class="row text-center align-items-center justify-content-center">
    <div class="col-12">
        <span style="font-size: 1.75rem;">included</span>
    </div>
    <div class="col-12 col-sm-6 col-md-4 pb-5">
        <div class="slider slider-brands">
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-bold"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="far fa-square"></i>
                        <i class="fas fa-bold fa-inverse" data-fa-transform="shrink-6"></i>
                    </span>
                </div>
                <a href="https://getbootstrap.com/" target="_blank" class="d-block label">Bootstrap 4</a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-font-awesome-flag"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="far fa-square"></i>
                        <i class="fab fa-font-awesome-flag fa-inverse" data-fa-transform="shrink-6"></i>
                    </span>
                </div>
                <a href="https://fontawesome.com/" target="_blank" class="d-block label">Fontawesome 5</a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-images"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-square"></i>
                        <i class="fas fa-image fa-inverse" data-fa-transform="shrink-7"></i>
                        <i class="fas fa-chevron-left fa-inverse" data-fa-transform="shrink-13 left-6"></i>
                        <i class="fas fa-chevron-right fa-inverse" data-fa-transform="shrink-13 right-6"></i>
                    </span>
                </div>
                <a href="http://kenwheeler.github.io/slick/" target="_blank" class="d-block label">Slick Carousel</a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-image"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-square"></i>
                        <i class="fas fa-image fa-inverse" data-fa-transform="shrink-4"></i>
                        <i class="fas fa-sync" data-fa-transform="shrink-14 up-2.5 right-4"></i>
                    </span>
                </div>
                <a href="https://www.andreaverlicchi.eu/lazyload/" target="_blank" class="d-block label">LazyLoad Image</a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-css3"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-square"></i>
                        <i class="fas fa-user-secret fa-inverse" data-fa-transform="shrink-4"></i>
                        <i class="fab fa-css3" data-fa-transform="shrink-14 down-4 right-3.5"></i>
                        <i class="fab fa-html5" data-fa-transform="shrink-14 down-4 left-3.5"></i>
                    </span>
                </div>
                <a href="https://www.npmjs.com/package/cssuseragent" target="_blank" class="d-block label">CSS User Agent</a>
            </div>
            <div class="slider-item">
                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 up-4 left-4"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 down-0 left-5.5"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 down-4.2 right-4"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-13 down-4 left-2"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-13"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-14 right-5"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-14 up-5"></i>
                    </span>
                </div>
                <a href="https://github.com/insites/cookieconsent" target="_blank" class="d-block label">Cookieconsent 3</a>
            </div>
        </div>
    </div>
    <div class="col-12 pb-5">
        <div class="row">
            <div class="col-12 col-md-6 pb-5 pb-md-0">
                <h3 class="pb-2">LazyLoad Example</h3>
                <img data-src="http://via.placeholder.com/266x140/2E97BF/212121?text=LazyLoad%20Image" alt="image" class="img-fluid"/>
            </div>
            <div class="col-12 col-md-6">
                <h3 class="pb-2">CSS User Agent Monitor</h3>
                <div class="cssua-monitor"></div>
            </div>
        </div>
    </div>
</div>
