<?php
// if is Docker
if (isset($_ENV['docker']) && $_ENV['docker']) {
    /** @var GulpSkeleton $gs **/
    $gs->setBaseUrl('http://localhost:7701/');
}

// if is BrowserSync
if (isset($_SERVER['HTTP_ACCEPT_ENCODING']) && $_SERVER['HTTP_ACCEPT_ENCODING'] === 'identity') {
    /** @var GulpSkeleton $gs **/
    $gs->setBaseUrl('http://localhost:3000/');
}

$imagePlaceholder = "data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 %w %h'%3e%3c/svg%3e";
$theme = isset($_COOKIE['theme']) && in_array($_COOKIE['theme'], ['dark', 'light']) ? $_COOKIE['theme'] : 'dark';
?>

<!DOCTYPE html>
<html lang="<?= $lang['lang']; ?>" class="no-js" data-bs-theme="<?= $theme; ?>">
    <head>
        <script>
            // setCookie('name', 'value', exdays);
            // getCookie('name');
            function setCookie(e,t,n){var o=new Date;o.setTime(o.getTime()+24*n*60*60*1e3);var i="expires="+o.toUTCString();document.cookie=e+"="+t+";"+i+";path=/"}function getCookie(e){for(var t=e+"=",n=decodeURIComponent(document.cookie).split(";"),o=0;o<n.length;o++){for(var i=n[o];" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(t))return i.substring(t.length,i.length)}return""}
            var cookiesAllowed = getCookie('cookieconsent_status') !== 'deny';
        </script>
        
        <title><?= $gs->getPageTitle(); ?></title>
        <!-- <base href="<?= $gs->getBaseUrl(); ?>"> -->
        <base href="/">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="keywords" content="<?= $lang['meta-keywords']; ?>"/>
        <meta name="description" content="<?= $lang['meta-description']; ?>">
        <meta name='robots' content="<?= $lang['meta-robots']; ?>">
        <meta name="author" content="<?= $lang['meta-author']; ?>">
        <!-- Facebook, LinkedIn -->
        <meta property="fb:admins" content="<?= $lang['meta-fbAdmins']; ?>"/>
        <meta property="fb:app_id" content="<?= $lang['meta-fbAppId']; ?>"/>
        <meta property="og:type" content="<?= $lang['meta-type']; ?>"/>
        <meta property="og:title" content="<?= $lang['meta-title']; ?>"/>
        <meta property="og:description" content="<?= $lang['meta-description']; ?>"/>
        <meta property="og:image" content="<?= $gs->getBaseUrl() . $lang['meta-socialMediaImage']; ?>"/>
        <meta property="og:site_name" content="<?= $lang['meta-siteName']; ?>"/>
        <meta property="og:url" content="<?= $gs->getCurrentUrl(); ?>"/>
        <meta property="og:locale" content="<?= $lang['locale']; ?>"/>
        <meta property="article:publisher" content="<?= $lang['meta-publisher']; ?>"/>
        <!-- Twitter -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="<?= $lang['meta-twitterSite']; ?>">
        <meta name="twitter:title" content="<?= $lang['meta-title']; ?>">
        <meta name="twitter:description" content="<?= $lang['meta-description']; ?>">
        <meta property="twitter:image" content="<?= $gs->getBaseUrl() . $lang['meta-socialMediaImage']; ?>">
        <link rel="me" href="<?= $lang['meta-twitterUrl']; ?>">
        <link rel="canonical" href="<?= $gs->getCurrentUrl(); ?>"/>
        <link rel="alternate" hreflang="x-default" href="<?= $gs->getCurrentUrl(); ?>"/>
        <!--<link rel="alternate" type="application/rss+xml" title="" href="<?= $lang['meta-rssUrl']; ?>"/>-->
        <!-- Favicons -->
        <link rel="icon" type="image/x-icon" href="/img/favicons/favicon.ico">
        <link rel="icon" type="image/png" sizes="16x16" href="/img/favicons/favicon-16x16.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/img/favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="48x48" href="/img/favicons/favicon-48x48.png">
        <link rel="manifest" href="/img/favicons/manifest.webmanifest">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="theme-color" content="#000">
        <meta name="application-name" content="Gulp Skeleton">
        <link rel="apple-touch-icon" sizes="57x57" href="/img/favicons/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/img/favicons/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/img/favicons/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/img/favicons/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/img/favicons/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/img/favicons/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/img/favicons/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/img/favicons/apple-touch-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="167x167" href="/img/favicons/apple-touch-icon-167x167.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/favicons/apple-touch-icon-180x180.png">
        <link rel="apple-touch-icon" sizes="1024x1024" href="/img/favicons/apple-touch-icon-1024x1024.png">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
        <meta name="apple-mobile-web-app-title" content="Gulp Skeleton">
        <link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-640x1136.png">
        <link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-1136x640.png">
        <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-750x1334.png">
        <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-1334x750.png">
        <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1125x2436.png">
        <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2436x1125.png">
        <link rel="apple-touch-startup-image" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1170x2532.png">
        <link rel="apple-touch-startup-image" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2532x1170.png">
        <link rel="apple-touch-startup-image" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1179x2556.png">
        <link rel="apple-touch-startup-image" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2556x1179.png">
        <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-828x1792.png">
        <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-1792x828.png">
        <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1242x2688.png">
        <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2688x1242.png">
        <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1242x2208.png">
        <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2208x1242.png">
        <link rel="apple-touch-startup-image" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1284x2778.png">
        <link rel="apple-touch-startup-image" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2778x1284.png">
        <link rel="apple-touch-startup-image" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1290x2796.png">
        <link rel="apple-touch-startup-image" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2796x1290.png">
        <link rel="apple-touch-startup-image" media="(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1488x2266.png">
        <link rel="apple-touch-startup-image" media="(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2266x1488.png">
        <link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1536x2048.png">
        <link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2048x1536.png">
        <link rel="apple-touch-startup-image" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1620x2160.png">
        <link rel="apple-touch-startup-image" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2160x1620.png">
        <link rel="apple-touch-startup-image" media="(device-width: 820px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1640x2160.png">
        <link rel="apple-touch-startup-image" media="(device-width: 820px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2160x1640.png">
        <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1668x2388.png">
        <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2388x1668.png">
        <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-1668x2224.png">
        <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2224x1668.png">
        <link rel="apple-touch-startup-image" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/img/favicons/apple-touch-startup-image-2048x2732.png">
        <link rel="apple-touch-startup-image" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" href="/img/favicons/apple-touch-startup-image-2732x2048.png">
        <meta name="msapplication-TileColor" content="#000">
        <meta name="msapplication-TileImage" content="/img/favicons/mstile-144x144.png">
        <meta name="msapplication-config" content="/img/favicons/browserconfig.xml">
        <link rel="yandex-tableau-widget" href="/img/favicons/yandex-browser-manifest.json">
        
        <link rel="stylesheet" href="css/styles.css?v=7.0.0-dev">
        <script type="application/javascript">
            // if cookies allowed - load tracking code
            if (cookiesAllowed) {
                // Google Analaytics, Google Tag Manager, ...
//                var s = document.createElement('script');
//                s.type = 'text/javascript';
//                s.async = true;
//                s.src = 'https://www.googletagmanager.com/gtag/js?id=UA-NUMBER-X';
//                var h = document.getElementsByTagName('head')[0];
//                h.appendChild(s, h);
//            
//                window.dataLayer = window.dataLayer || [];
//                function gtag(){dataLayer.push(arguments);}
//                gtag('js', new Date());
//                gtag('config', 'UA-NUMBER-X', {'anonymize_ip': true});
            }
        </script>
    </head>
    <body>
        <header>
            <div class="container">
                <?php include __DIR__ . '/../partial/header.phtml'; ?>
            </div>
        </header>
        <main>
            <div class="container">
                <?php include __DIR__ . '/../' . $gs->getTemplate() . '.phtml'; ?>
            </div>
        </main>
        <footer>
            <div class="container">
                <?php include __DIR__ . '/../partial/footer.phtml'; ?>
            </div>
        </footer>
        <?php include __DIR__ . '/../partial/modal.phtml'; ?>
        <script src="js/scripts.js?v=7.0.0-dev"></script>
    </body>
</html>
