<div class="row">
    <div class="col-12">
        <div class="btn-group dropup">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-globe"></i>&nbsp;
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="<?php $gs->getPathFor($gs->getRouteName(), 'de_de'); ?>">Deutsch</a>
                <a class="dropdown-item" href="<?php $gs->getPathFor($gs->getRouteName(), 'en_us'); ?>">English</a>
            </div>
        </div>
        <span class="float-end">
            <?= $lang['version'] . ' ' . $gs->getVersion(); ?>
        </span>
    </div>
</div>
