<div class="row">
    <div class="col-12 pb-3">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a href="<?php $gs->getPathFor('index'); ?>" class="nav-link"><?= $lang['link-home']; ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php $gs->getPathFor('about'); ?>" class="nav-link"><?= $lang['link-about']; ?></a>
            </li>
            <li class="nav-item">
                <a href="/foobar" class="nav-link"><?= $lang['link-error']; ?></a>
            </li>
        </ul>
    </div>
</div>
