<div class="row">
    <div class="col-12 pb-3">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a href="<?php $gs->getPathFor('index'); ?>" class="nav-link"><?= $lang['link-home']; ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php $gs->getPathFor('about'); ?>" class="nav-link"><?= $lang['link-about']; ?></a>
            </li>
            <li class="nav-item">
                <a href="/foobar" class="nav-link"><?= $lang['link-error']; ?></a>
            </li>
            <li class="nav-item">
                <span class="nav-link d-inline-block">
                    <span class="theme-switcher dark">
                        <i class="fas fa-sun pe-1" aria-hidden="true"></i>
                        <i class="fas fa-moon ps-1" aria-hidden="true"></i>
                    </span>
                </span>
            </li>
        </ul>
    </div>
</div>
