<div class="modal fade" id="cookie-policy" tabindex="-1" role="dialog" aria-labelledby="cookie-policy-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?= $lang['cookie-policy-title']; ?></h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <?= $lang['cl-message']; ?><br/>
                <button class="btn btn-primary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#cookie-policy-collapse" aria-expanded="false" aria-controls="cookie-policy-collapse"><?= $lang['cpm-sdi']; ?></button>
                
                <div class="collapse" id="cookie-policy-collapse">
                    <div class="table-responsive mt-3">
                        <table class="table table-striped table-dark">
                            <thead>
                                <tr>
                                    <th scope="col"><span class="text-nowrap"><?= $lang['name']; ?></span></th>
                                    <th scope="col"><span class="text-nowrap"><?= $lang['provider']; ?></span></th>
                                    <th scope="col"><span class="text-nowrap"><?= $lang['purpose']; ?></span></th>
                                    <th scope="col"><span class="text-nowrap"><?= $lang['expires']; ?></span></th>
                                    <th scope="col"><span class="text-nowrap"><?= vsprintf($lang['type'], ['']); ?></span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>PHPSESSID</td>
                                    <td>gulp.codelinered.net</td>
                                    <td><?= $lang['cpm-php']; ?></td>
                                    <td><?= $lang['session']; ?></td>
                                    <td><span class="text-nowrap"><?= vsprintf($lang['type'], ['1']); ?></span></td>
                                </tr>
                                <tr>
                                    <td>cookieconsent_status</td>
                                    <td>gulp.codelinered.net</td>
                                    <td><?= $lang['cpm-cc-status']; ?></td>
                                    <td><span class="text-nowrap"><?= vsprintf($lang['year'], ['1']); ?></span></td>
                                    <td><span class="text-nowrap"><?= vsprintf($lang['type'], ['2']); ?></span></td>
                                </tr>
                                <tr>
                                    <td>current_locale</td>
                                    <td>gulp.codelinered.net</td>
                                    <td><?= $lang['cpm-current-locale']; ?></td>
                                    <td><span class="text-nowrap"><?= vsprintf($lang['year'], ['1']); ?></span></td>
                                    <td><span class="text-nowrap"><?= vsprintf($lang['type'], ['2']); ?></span></td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="pb-3">
                            <?= $lang['cpm-type1']; ?><br/>
                            <?= $lang['cpm-type2']; ?><br/>
                            <?= $lang['cpm-type3']; ?><br/>
                            <?= $lang['cpm-type4']; ?><br/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
